apiVersion: v2
appVersion: "0.48.1"
description: Prometheus operator helm chart
name: kube-prometheus-stack
version: 0.48.1
dependencies:
  - name: kube-prometheus-stack
    version: "16.12.0"
    repository: "@prometheus-community"
