apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: prometheus-operator-prometheus
    release: prometheus-operator
  name: prometheus-operator-prometheus-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - prometheus-operator-prometheus
  resources:
  - podsecuritypolicies
  verbs:
  - use
