---
# Source: etcd-operator/templates/operator-deployment.yaml

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: etcd-operator-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.8.3"
    app: etcd-operator
    heritage: Tiller
    release: etcd-operator
spec:
  selector:
    matchLabels:
      app: etcd-operator-etcd-operator-etcd-operator
      release: etcd-operator
  replicas: 1
  template:
    metadata:
      name: etcd-operator-etcd-operator-etcd-operator
      labels:
        app: etcd-operator-etcd-operator-etcd-operator
        release: etcd-operator
    spec:
      serviceAccountName: etcd-operator-etcd-operator-etcd-operator
      containers:
      - name: etcd-operator-etcd-operator-etcd-operator
        image: "quay.io/coreos/etcd-operator:v0.9.3"
        imagePullPolicy: Always
        command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
